name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv env  # Create virtual environment
        . env/bin/activate  # Activate virtual environment
        pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Run the web application
      run: |
        . env/bin/activate  # Activate virtual environment
        nohup make run &  # Run the application in the background with nohup
        sleep 60  # Allow some time for the server to start

    - name: Test the server
      run: |
        curl http://localhost:3000
